services:
  decotv:
    build: .
    container_name: decotv
    ports:
      - "8080:8080" # 将内部 8080 端口映射到主机的 8080 端口
    environment:
      - PASSWORD=${PASSWORD:-your_password} # 可将 your_password 修改为你想要的密码，默认为 your_password
      - PORT=8080
      - CORS_ORIGIN=*
      - DEBUG=false
    restart: unless-stopped
    # 可选：如果需要持久化数据，取消注释下面的 volumes 配置
    # volumes:
    #   - ./data:/app/data

  # 使用预构建镜像的版本（推荐生产环境使用）
  decotv-prod:
    image: katelya77/decotv:latest
    container_name: decotv-prod
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=${PASSWORD:-your_password}
      - PORT=8080
      - CORS_ORIGIN=*
    restart: unless-stopped
    profiles:
      - prod
